name: Sync docs to Wiki

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Sync docs to Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          path: docs
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
